name: Check

on:
  pull_request:
    types: [opened, synchronize]
    push:
      branches:
        - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Installing node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn install
      - name: Run lint
        run: yarn run lint
      - name: Run format check
        run: yarn run format
      - name: Run type check
        run: yarn run typecheck
      - name: Run build
        run: yarn run build